---
galaxy_info:
  role_name: haproxy
  description: setup haproxy load balancer
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0
  platforms:
    - name: EL
      versions: [ 10, 9, 8 ]
    - name: Ubuntu
      versions: [ 24.04, 22.04 ]
    - name: Debian
      versions: [ 13, 12 ]
  galaxy_tags:
    - pigsty
    - haproxy
...