---
galaxy_info:
  role_name: redis_remove
  description: remove redis instance & cluster from pigsty nodes
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0
  platforms:
    - name: EL
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: Debian
      versions: [all]
  galaxy_tags:
    - pigsty
    - redis
    - uninstall
...
