---
#-----------------------------------------------------------------
# REDIS_REMOVE
#-----------------------------------------------------------------
redis_uninstall: false            # uninstall redis & redis_exporter? false by default

#-----------------------------------------------------------------
# REDIS (REFERENCE)
#-----------------------------------------------------------------
redis_fs_main: /data              # main fs mountpoint for redis data
redis_safeguard: false            # prevent purging running redis instance?
redis_clean: true                 # purging existing redis during initialization?
#-----------------------------------------------------------------
# VICTORIA (Reference)
#-----------------------------------------------------------------
vmetrics_enabled: true            # enable prometheus on this infra node?
victoria_sd_dir: /data/vm/targets # victoria file service discovery directory
...