---
#-----------------------------------------------------------------
# REDIS_REMOVE
#-----------------------------------------------------------------
redis_safeguard: false            # prevent purging running redis instance?
redis_rmdata: true                # remove redis data dir? (/data/redis/...)
redis_uninstall: false            # uninstall redis & redis_exporter packages?

#-----------------------------------------------------------------
# REDIS (REFERENCE)
#-----------------------------------------------------------------
redis_fs_main: /data              # main fs mountpoint for redis data

#-----------------------------------------------------------------
# VECTOR (Reference)
#-----------------------------------------------------------------
vector_enabled: true              # enable vector log collector?
...