---
#-----------------------------------------------------------------
# CODE
#-----------------------------------------------------------------
code_enabled: false               # enable code-server on this node?
code_port: 8443                   # code-server listen port
code_home: /fs/code               # code-server working directory (open folder)
code_data: /data/code             # code-server user data directory
code_password: 'Code.Server'      # code-server password
code_gallary: 'openvsx'           # code-server extension gallery, can be microsoft or openvsx
code_extensions: []               # extensions to be installed
...
