---
galaxy_info:
  role_name: infra
  description: init infra module on pigsty managed nodes
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0 for Grafana
  platforms:
    - name: EL
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: Debian
      versions: [all]
  galaxy_tags:
    - pigsty
    - grafana
    - victoria-metrics
    - victoria-logs
    - victoria-traces
    - vmalert
    - alertmanager
    - blackbox_exporter
...
