---
#--------------------------------------------------------------#
# Remove Pgbouncer                                   [pgbouncer]
#--------------------------------------------------------------#
- name: remove pgbouncer
  become: true
  ignore_errors: true
  block:

    - name: stop and disable pgbouncer service
      systemd: name=pgbouncer state=stopped enabled=no daemon_reload=yes

    - name: remove pgbouncer config data
      ignore_errors: true
      file: path=/etc/pgbouncer state=absent
...