---
galaxy_info:
  role_name: vibe
  description: deploy development tools (claude, code-server, jupyter) on pigsty managed nodes
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0
  platforms:
    - name: EL
      versions: [ 10, 9, 8, 7 ]
    - name: Ubuntu
      versions: [ 24.04, 22.04, 20.04 ]
    - name: Debian
      versions: [ 13, 12, 11 ]
  galaxy_tags:
    - pigsty
    - vibe
    - claude
    - code-server
    - jupyter
    - devbox
...
