---
galaxy_info:
  role_name: juice
  description: 'JuiceFS with PostgreSQL backend for PITR-capable file system'
  min_ansible_version: "2.9"
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0
  platforms:
    - name: EL
      versions: [ 8, 9, 10 ]
    - name: Ubuntu
      versions: [ 22.04, 24.04 ]
    - name: Debian
      versions: [ 12, 13 ]
  galaxy_tags:
    - pigsty
    - juice
    - juicefs
    - postgresql
    - filesystem
...
