---
#--------------------------------------------------------------#
# JUICE
#--------------------------------------------------------------#
juice_enabled: true                   # enable juicefs module
# juice_pgurl: postgres://u:p@h:5432/db   # [REQUIRED] metadata backend
juice_name: jfs                       # juicefs filesystem name
juice_mount: /data/juice              # mountpoint, /data/juice by default
juice_cache: /data/cache              # juicefs cachedir, /data/cache by default
juice_format_options: ''              # juicefs format options (e.g. --storage postgres --bucket ...)
juice_mount_options: ''               # juicefs mount options (e.g. --buffer-size 300)
juice_port: 9567                      # juicefs metrics port
juice_owner: root                     # mountpoint os user owner
juice_group: root                     # mountpoint os user group
juice_mode: '0755'                    # mountpoint directory mode
...
