---
#-----------------------------------------------------------------
# VICTORIA (Reference)
#-----------------------------------------------------------------
victoria_sd_dir: /data/vm/targets # victoria file service discovery directory
#-----------------------------------------------------------------
# VECTOR (Reference)
#-----------------------------------------------------------------
vector_enabled: true              # enable vector log collector?
vector_clean: true                # purge vector data dir during node_remove?
vector_data: /data/vector         # vector data dir, /data/vector by default
#-----------------------------------------------------------------
# NODE_VIP (Reference)
#-----------------------------------------------------------------
vip_enabled: false                # enable vip on this node cluster?
#-----------------------------------------------------------------
# NODE_EXPORTER (Reference)
#-----------------------------------------------------------------
node_exporter_enabled: true       # setup node_exporter on instance
...