---
#-----------------------------------------------------------------
# VECTOR (Reference)
#-----------------------------------------------------------------
vector_enabled: true              # enable vector log collector?
vector_clean: true                # purge vector data dir during node_remove?
vector_data: /data/vector         # vector data dir, /data/vector by default

#-----------------------------------------------------------------
# NODE (Reference)
#-----------------------------------------------------------------
node_crontab_overwrite: true      # overwrite or append to `/etc/crontab`?
#-----------------------------------------------------------------
# NODE_VIP (Reference)
#-----------------------------------------------------------------
vip_enabled: false                # enable vip on this node cluster?
#-----------------------------------------------------------------
# NODE_EXPORTER (Reference)
#-----------------------------------------------------------------
node_exporter_enabled: true       # setup node_exporter on instance
...