---
#-----------------------------------------------------------------
# JUPYTER
#-----------------------------------------------------------------
jupyter_enabled: false            # enable jupyter on this node?
jupyter_port: 8888                # jupyter listen port
jupyter_home: /fs/jupyter         # jupyter working directory (notebook root)
jupyter_data: /data/jupyter       # jupyter data directory (config, bindfile, bindfile)
jupyter_password: 'Jupyter.Lab'   # jupyter login token
jupyter_venv: /data/venv          # python venv path where jupyter is installed
...
